---
deployment:
  tasks:

    - export DEPLOYPATH=~/public_html/
    #- /bin/mkdir ~/public_html/linkbits_cotizaciones2
    #- /bin/chmod 755 ~/public_html/linkbits_cotizaciones2
    #- /bin/cp index.html $DEPLOYPATH
    - /bin/cp -r -u ~/repositories/linkbits_cotizaciones/ $DEPLOYPATH
    - /bin/chmod 755 ~/public_html/linkbits_cotizaciones
 