---
deployment:
  tasks:
    - chmod 755 ~/repositories
    - chmod 755 ~/repositories/linkbits_cotizaciones

    - export DEPLOYPATH=~/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp page2.html $DEPLOYPATH
    - /bin/cp page3.html $DEPLOYPATH
    - /bin/cp page4.html $DEPLOYPATH
    - /bin/cp page5.html $DEPLOYPATH
